### ISSUE TITLE
Advanced - memo format once submitted

### ISSUE THREAD

**Issue by loristokes** [inkdlab/writing-game-week3#30]
Here is a sample screenshot of what the player will see when he/she has completed the advanced-level memo. 

![screen shot 2017-01-20 at 1 39 51 pm](https://cloud.githubusercontent.com/assets/24571312/22160940/ff6e5a5a-df15-11e6-8a9a-e3dbdfe12342.png)

From Julie: Since the screen requires the memo’s wording to go off screen (the ruler at the bottom is helpful), how will this work when the player adds bullets on the previous screen and then comes to this one? Memos are not just about content; layout plays a significant role in their creation and effectiveness, so how can the correct layout be reinforced in this section of the game? Perhaps it might be possible to have the student build the memo on the previous screen and then forward it to the instructor from that point instead of progressing to this screen to send.  That would allow us to omit this screen.  What do you think?

**Comment by jaytay579** [comment]
To elaborate, I think Julie's concern here is that the memo preview may not have the same format, exactly, as how the students set it up. So, three things:

FIRST, we need to make sure we have some way of letting the students create rudimentary formatting. We don't have to go to a full formatted text field (though that should be a part of the spec for the next revision) but we should have some interpretation for bullet points, which are needed for the memo. One idea might be allowing a line starting with * to become a bullet line (as Word and some markup formats allow), though I'm not sure if that is intuitive enough.

SECOND, we need to make sure whatever formatting the students include is preserved/saved/re-rendered correctly when sent to the instructor. The instructor can't fairly grade the email if they don't know where the student put in line breaks, bullet points, etc.

THIRD, if we get through the first two items, we should make sure this "preview screen" shows the memo as the instructor will see it. However, this is lower priority than the first two items, since we could allow the previous screen to be "save and send", potentially.  But, to reply to Lori's and Julie's thoughts, I think there is value in letting the students review their formatting (especially if we're enhancing the markup by converting * to a bullet point or something), so this would be useful to have.

**Comment by aarthyadityan** [comment]
The review screen does preserve any line breaks that the student uses in the form, and the text in the review screen generally only scrolls vertically. The reason the text goes off screen in that image, with a horizontal ruler added, is because something like 'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm' is one word and so it cannot wrap to the next line (although I think there might be a css solution to this).

If a student adds bullets to the form, it will be retained in the review screen. I just tested this with pasting a bullet into the form (I still have to test that it is retained in the email). We don't have an easy way for the student to bullets yet though. We could possibly have a button for 'Add bullet point' or something like that. What do you think? 

I agree with @jaytay579 that we probably need to have some more formatting options. Which ones do we definitely need for this module, @loristokes? I can tinker with adding those this weekend.

**Comment by loristokes** [comment]
We just need those indented bullets in the body.
