### ISSUE TITLE
Advanced - input boxes move to next line on Chrome when resized

### ISSUE THREAD

**Issue by aarthyadityan** [inkdlab/writing-game-week3#31]
<img width="1005" alt="2017-01-20 03 27 19 pm" src="https://cloud.githubusercontent.com/assets/21074048/22164394/0fc1ada8-df25-11e6-8459-29edbec0ccef.png">

**Comment by motwaniy** [comment]
That's probably due to browser incompatibility issue, because it's working fine for me on chrome but differently on firefox (as aarthy's screenshot).
Here is my screenshot from chrome!
@tiagodcosta can you please look into this.  
![screen shot 2017-01-23 at 1 14 47 pm](https://cloud.githubusercontent.com/assets/21201005/22216765/581672c8-e16e-11e6-9aa6-dae5214e4204.png)

**Comment by jaytay579** [comment]
Just a reminder to always specify operating system (MacOS/Windows/etc) and browser version number when reporting a browser incompatibility issue. Issues sometimes vary across operating systems, and we don't always have the latest browser versions in the lab (plus we should test on older versions to some extent, too!)

**Comment by aarthyadityan** [comment]
Good point @jaytay579 ! The original issue was on Chrome Version 55.0.2883.95 on MacOS
